TICKS_PER_SECOND = 50
MAP_SIZE_X = 1000
MAP_SIZE_Y = 1000
AGENT_SIZE = 5
PREDATOR_SIZE = 10
# task parameters
TASK_SIZE = 10
TASK_ATTRACTION_RADIUS = 30
TASK_SCOPE = TICKS_PER_SECOND * 2  # one agent needs n seconds to fulfill a task
TASK_FORCE_SCALE = 10
